trigger:
  branches:
    include:
    - main

pool:
  vmImage: "ubuntu-latest"

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: "1.1.2"

- task: TerraformTaskV1@0
  displayName: "Terraform Init"
  inputs:
    provider: "azurerm"
    command: "init"

- task: TerraformTaskV1@0
  displayName: "Terraform Validate"
  inputs:
    provider: "azurerm"
    command: "validate"

- task: TerraformTaskV1@0
  displayName: "Terraform Plan"
  inputs:
    provider: "azurerm"
    command: "plan"
    commandOptions: "-out=tfplan"

- task: TerraformTaskV1@0
  displayName: "Terraform Apply"
  inputs:
    provider: "azurerm"
    command: "apply"
    commandOptions: "-auto-approve"
    environmentServiceName: "your_azure_subscription"
